### ISSUE TITLE
missing file "xodr_export.h" 

### ISSUE THREAD

**Issue by gammagandalf** [javedulu/ad-xolib#5]
Thanks a lot for your helpful project. I've cloned the repository and its submodules, but there is no file like "xodr_export.h" detectable within the project (but it is used in "xodr.h"). Is this an issue from cloning or is there an other workaround to get access to this file?

**Comment by javedulu** [comment]
It should be generated when you build with CMake , it should be in binary directory

**Comment by gammagandalf** [comment]
yeah that's right, thanks a lot
