### ISSUE TITLE
What code generator did you use to generate the c++ header and source file from xsd schema?

### ISSUE THREAD

**Issue by runpiw** [javedulu/ad-xolib#6]

**Comment by javedulu** [comment]
That's an internal project which uses xsd schema to c++

**Comment by Alphabaijinde** [comment]
Do you have  the OpenDRIVE 1.6 > UML_Model ?

**Comment by javedulu** [comment]
yes i have written it to convert general UML to OpenDrive / Open Scenario

**Comment by Alphabaijinde** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到您的邮件，会尽快回复的。
